# Generated by Django 4.2.1 on 2023-06-15 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buhead',
            fields=[
                ('Bu_head_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('candidate_name', models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False)),
                ('interview_status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'candidate_list',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=50, null=True)),
                ('cEmail', models.EmailField(max_length=254, null=True)),
                ('cUrl', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='router_specifications')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eFname', models.CharField(max_length=50, null=True)),
                ('eLname', models.CharField(max_length=50, null=True)),
                ('eEmail', models.EmailField(max_length=200, null=True)),
                ('ePhone', models.CharField(max_length=50, null=True)),
                ('eExperience', models.IntegerField(default=0, null=True)),
                ('eskills', models.CharField(max_length=100, null=True)),
                ('eRole', models.CharField(max_length=50, null=True)),
                ('eMP_Type', models.CharField(max_length=30, null=True)),
                ('estatus', models.CharField(max_length=100, null=True)),
                ('leadsoc_joining_date', models.DateField(null=True)),
                ('customer_start_date', models.DateField(null=True)),
                ('remarks', models.CharField(max_length=30, null=True)),
                ('refer_Customer', models.ForeignKey(db_column='cName', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Customer_Requirements',
            fields=[
                ('Requirement_Id', models.IntegerField(unique=True)),
                ('Customer_Requirement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Required_skills', models.TextField()),
                ('Job_Description', models.TextField()),
                ('Required_Experience', models.IntegerField(default=0)),
                ('Open_positions', models.IntegerField(default=0)),
                ('remain_positions', models.IntegerField(default=0)),
                ('Position_Status', models.CharField(max_length=10)),
                ('Sales_Incharge', models.CharField(max_length=50)),
                ('Bu_head', models.CharField(default='RAGHU V T', max_length=50)),
                ('customers', models.ForeignKey(blank=True, db_column='cName', on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer')),
            ],
            options={
                'db_table': 'customer_requirements',
            },
        ),
        migrations.CreateModel(
            name='addEmpToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eFname', models.CharField(max_length=100, null=True)),
                ('eLname', models.CharField(max_length=100, null=True)),
                ('eskills', models.CharField(max_length=100, null=True)),
                ('estatus', models.CharField(max_length=100, null=True)),
                ('refer_Customer', models.ForeignKey(db_column='cName', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer')),
            ],
            options={
                'db_table': 'addemptocustomer',
            },
        ),
    ]
