# Generated by Django 4.2.1 on 2023-05-17 10:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=50, null=True)),
                ('cEmail', models.EmailField(max_length=254)),
                ('cUrl', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='router_specifications')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eFname', models.CharField(max_length=50, null=True)),
                ('eLname', models.CharField(max_length=50, null=True)),
                ('eEmail', models.EmailField(max_length=200, null=True)),
                ('ePhone', models.CharField(blank=True, max_length=50)),
                ('eExperience', models.IntegerField(default=0)),
                ('eskills', models.CharField(max_length=100, null=True)),
                ('eRole', models.CharField(max_length=50, null=True)),
                ('eMP_Type', models.CharField(max_length=30, null=True)),
                ('estatus', models.CharField(choices=[('Free', 'Deployed'), ('Free', 'Deployed')], max_length=100, null=True)),
                ('leadsoc_joining_date', models.DateField()),
                ('customer_start_date', models.DateField(default=datetime.datetime(2023, 5, 17, 15, 32, 39, 411079))),
                ('remarks', models.CharField(max_length=30, null=True)),
                ('refer_Customer', models.ForeignKey(db_column='cName', on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Customer_Requirements',
            fields=[
                ('Requirement_Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Customer_Requirement_id', models.IntegerField(default=0)),
                ('Required_skills', models.TextField()),
                ('Job_Description', models.TextField()),
                ('Required_Experience', models.IntegerField(default=0)),
                ('Open_positions', models.IntegerField(default=0)),
                ('Position_Status', models.CharField(max_length=10)),
                ('Current_open_position', models.IntegerField(default=0)),
                ('Candidate_status', models.CharField(max_length=20)),
                ('Sales_Incharge', models.CharField(max_length=50)),
                ('Candidate_List', models.CharField(max_length=100, null=True)),
                ('customers', models.ForeignKey(db_column='cName', on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer')),
            ],
            options={
                'db_table': 'customer_requirements',
            },
        ),
    ]
