# Generated by Django 4.2.1 on 2023-05-17 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 16, 5, 3, 987766)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ePhone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
