# Generated by Django 4.2.1 on 2023-05-17 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0003_alter_employee_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 16, 8, 23, 591363)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='leadsoc_joining_date',
            field=models.DateField(null=True),
        ),
    ]
