# Generated by Django 4.2.1 on 2023-05-17 10:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0005_alter_employee_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 16, 11, 33, 434799), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='refer_Customer',
            field=models.ForeignKey(db_column='cName', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer'),
        ),
    ]
