# Generated by Django 4.2.1 on 2023-05-17 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0008_alter_employee_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 17, 17, 38, 33, 539996), null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='estatus',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
