# Generated by Django 4.2 on 2023-05-18 05:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0009_alter_employee_customer_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 18, 10, 57, 54, 855414), null=True),
        ),
    ]
