# Generated by Django 4.2 on 2023-05-18 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0010_alter_employee_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cEmail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cUrl',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 18, 11, 1, 49, 289087), null=True),
        ),
    ]
