# Generated by Django 4.2 on 2023-05-18 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0011_alter_customer_cemail_alter_customer_curl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 18, 11, 19, 16, 155959), null=True),
        ),
    ]
