# Generated by Django 4.2 on 2023-05-19 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0014_alter_employee_customer_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 19, 9, 53, 4, 423693), null=True),
        ),
    ]
