# Generated by Django 4.2.1 on 2023-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0015_alter_employee_customer_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_requirements',
            old_name='Current_open_position',
            new_name='remain_positions',
        ),
        migrations.RemoveField(
            model_name='customer_requirements',
            name='Candidate_List',
        ),
        migrations.RemoveField(
            model_name='customer_requirements',
            name='Candidate_status',
        ),
        migrations.AddField(
            model_name='customer_requirements',
            name='Bu_head',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='customer_start_date',
            field=models.DateField(null=True),
        ),
    ]
