# Generated by Django 4.2.1 on 2023-05-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0016_rename_current_open_position_customer_requirements_remain_positions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateList',
            fields=[
                ('candidate_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('interview_status', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'candidate_list',
            },
        ),
    ]
