# Generated by Django 4.2.1 on 2023-05-29 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0017_candidatelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_requirements',
            name='customers',
            field=models.ForeignKey(blank=True, db_column='cName', on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer'),
        ),
    ]
