# Generated by Django 4.2.1 on 2023-05-30 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_data', '0018_alter_customer_requirements_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatelist',
            name='candidate_name',
            field=models.CharField(default='', editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='addEmpToCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eFname', models.CharField(max_length=100, null=True)),
                ('eLname', models.CharField(max_length=100, null=True)),
                ('eskills', models.CharField(max_length=100, null=True)),
                ('refer_Customer', models.ForeignKey(db_column='cName', null=True, on_delete=django.db.models.deletion.CASCADE, to='emp_data.customer')),
            ],
            options={
                'db_table': 'addemptocustomer',
            },
        ),
    ]
